services:
  simtown-server:
    container_name: simtown-server
    image: ${IMAGE_NAME:-simtown}
    build:
      context: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: always
    tty: true
    command: ["bun", "src/server/server.ts"]
#   simtown-npc:
#     container_name: simtown-npc
#     image: ${IMAGE_NAME:-simtown}
#     build:
#       context: .
#     env_file:
#       - .env
#     network_mode: "host"
#     restart: always
#     tty: true
#     command: ["bun", "src/npc/client.ts"]
