services:
  simtown-server:
    image: ${IMAGE_NAME:-simtown}
    build:
      context: .
    ports:
      - "3000:3000"
    restart: always
    tty: true
    command: ["bun", "src/server/server.ts"]

  simtown-npc:
    image: ${IMAGE_NAME:-simtown}
    build:
      context: .
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    network_mode: "host"
    restart: always
    tty: true
    command: ["bun", "src/npc/client.ts"]
